fs     = require 'fs'
{exec} = require 'child_process'

appFiles  = [
  # omit src/ and .coffee to make the below lines a little shorter
  # main
  'javascripts/application'
  # models
  'javascripts/models/Location'
  # stores
  "javascripts/stores/Locations"
  # views
  'javascripts/views/Viewport'
  'javascripts/views/List'
  'javascripts/views/Map'

  # controllers

]

serverFiles = [
  'server'
]

task 'build', 'Build single application file from source files', ->
  appContents = new Array remaining = appFiles.length
  for file, index in appFiles then do (file, index) ->
    fs.readFile "#{file}.coffee", 'utf8', (err, fileContents) ->
      throw err if err
      appContents[index] = fileContents
      process() if --remaining is 0
  process = ->
    fs.writeFile 'javascripts/app.coffee', appContents.join('\n\n'), 'utf8', (err) ->
      throw err if err
      exec 'coffee --compile --bare javascripts/app.coffee', (err, stdout, stderr) ->
        throw err if err
        console.log stdout + stderr
        fs.unlink 'javascripts/app.coffee', (err) ->
          throw err if err
          console.log 'Finish processing front-end stuff.'
